spring: 
  datasource:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.tpool.DruidDaaSource
      connectionProperties: druid.stat.mergeSql=true
      initialSize: 10
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000