spring: 
  datasource:
      url: jdbc:mysql://192.168.1.91:3306/db_creditbusiness
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      initialSize: 10
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
